var _ = require('underscore');

var json = {
"events": {
			}
		};

		var datos = {
  "destacados": [
    {
      "src": "http:\/\/www.ciudaddemendoza.gov.ar\/bloques_destacados\/agenda_1573.jpg",
      "title": "Bardos Visuales"
    },
    {
      "src": "http:\/\/www.ciudaddemendoza.gov.ar\/bloques_destacados\/agenda_1435.jpg",
      "title": "PDF: Poes\u00eda en Diversos Formatos"
    }
  ],
  "actividades": [
    {
      "id": "19",
      "titulo": "Visit\u00e1 las diferentes ferias del Centro",
      "subtitulo": "Paseos comerciales de diversos art\u00edculos, en distintos puntos de nuestra Ciudad.",
      "contenido": "Plaza de las Artes: Jueves a domingo y feriados de 18 a 23hs. En Plaza Independencia. Facebook: Feria de Artesanos Plaza Independencia Mendoza.\/\/ Paseo Artesanal Estaci\u00f3n Cultural Ciudad: Viernes, s\u00e1bado, domingo y feriados de 11 a 23hs. En Av. Las Heras y Villalonga\/\/ Paseo Boulevard Mitre: Viernes, s\u00e1bado, domingo y feriados de 18 a 23hs. En Av. Mitre, entre Espejo y Las Heras.\/\/ Feria de libros y revistas usados: viernes y s\u00e1bados 10 a 13hs.En Portal Paseo Alameda, San Mart\u00edn y C\u00f3rdoba\/\/ Feria de Anticuarios, Numism\u00e1tica y Coleccionismo: Jueves,viernes y s\u00e1bados, 9 a 20hs. En Plazoleta Pellegrini. Av San Juan y Alem.",
      "direccion": "",
      "telefono": "",
      "mail": "",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "6",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "6143a603aaf293d8aaec149e78bde862caeb5fa0"
    },
    {
      "id": "1641",
      "titulo": "Bus vecino",
      "subtitulo": "Nuestros vecinos podr\u00e1n participar de un paseo para conocer nuestros lugares culturales y tur\u00edsticos.",
      "contenido": "Ser\u00e1n acompa\u00f1ados por un gu\u00eda, que contar\u00e1 la historia de nuestra Ciudad. El recorrido finaliza con una visita a una bodega.\n\nDe esta manera, ofrecemos un servicio que fortalece los v\u00ednculos y fideliza la relaci\u00f3n con los vecinos. Nuestro deseo es que puedan conocer y disfrutar los sitios m\u00e1s importantes de la Ciudad, para que sean excelentes anfitriones, conocedores y transmisores de su historia y su cultura.\n\nS\u00e1bados 7 y 14 de febrero. Gratuito con cupos limitados. Inscripci\u00f3n en:www.ciudaddemendoza.gov.ar\/ciudad-me-emociona",
      "direccion": "Recorrido por nuestra Ciudad",
      "telefono": "",
      "mail": "",
      "web": "",
      "dia_inicio": "7",
      "dia_fin": "7",
      "dias_semana": "64",
      "mes_inicio": "24181",
      "mes_fin": "24181",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "0",
      "precio": "Gratis.",
      "categoria_id": "1",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "34d4d9c86c7c6d56e6552ba420da437e362194b7"
    },
    {
      "id": "1642",
      "titulo": "Bus vecino",
      "subtitulo": "Nuestros vecinos podr\u00e1n participar de un paseo para conocer nuestros lugares culturales y tur\u00edsticos.",
      "contenido": "Ser\u00e1n acompa\u00f1ados por un gu\u00eda, que contar\u00e1 la historia de nuestra Ciudad. El recorrido finaliza con una visita a una bodega.\n\nDe esta manera, ofrecemos un servicio que fortalece los v\u00ednculos y fideliza la relaci\u00f3n con los vecinos. Nuestro deseo es que puedan conocer y disfrutar los sitios m\u00e1s importantes de la Ciudad, para que sean excelentes anfitriones, conocedores y transmisores de su historia y su cultura.\n\nS\u00e1bados 7 y 14 de febrero. Gratuito con cupos limitados. Inscripci\u00f3n en:www.ciudaddemendoza.gov.ar\/ciudad-me-emociona",
      "direccion": "Recorrido por nuestra Ciudad",
      "telefono": "",
      "mail": "",
      "web": "",
      "dia_inicio": "14",
      "dia_fin": "14",
      "dias_semana": "64",
      "mes_inicio": "24181",
      "mes_fin": "24181",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "0",
      "precio": "Gratis.",
      "categoria_id": "1",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "34d4d9c86c7c6d56e6552ba420da437e362194b7"
    },
    {
      "id": "969",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Danzas.",
      "contenido": "Danzas: Talleres  Municipales: Iniciaci\u00f3n a la danza ni\u00f1os: Marcela Pizarro. Lunes 9.30 hs (7y8 a\u00f1os), 11hs (5 y 6 a\u00f1os). $34\nFolclore adultos: Susana Dominguez. Lunes y viernes 15 hs. (inicial) y 16 hs. $34\nFolclore ni\u00f1os: Susana Dominguez. S\u00e1bados 10 hs a  11.30, y de 11. 30 a 13 hs. $34\n\nFlamenco: Adriana Colque. Lunes 15 hs. Martes 19 hs. $34 \/\/ Talleres Particulares:\nIniciaci\u00f3n a la danza: (5 y 6 a\u00f1os). Silvina Garc\u00eda. Mi\u00e9rcoles 16.30 hs. $100\nSalsa: Silvana Cascardo. S\u00e1bados 18 hs. $30 (por clase).\nBachata y ritmos caribe\u00f1os: S\u00e1bados 19 hs. $30 (por clase).\nDanzas afro: Carolina Bustos. Lunes y mi\u00e9rcoles 18 hs. $180\nDanza cl\u00e1sica: Enrique Lucero. Lunes y mi\u00e9rcoles 19.30 hs. $120\nTango: Cacho Orme\u00f1o. Viernes 19.30 hs. $30 (por clase).\nSalsa cubana \u2013 rueda casino: Silvana Cascardo. Mi\u00e9rcoles 21hs. $30 (por clase).\nRitmos latinos: Alexander Ibarguen. Martes y jueves 14 hs. $30 (por clase).",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "32d4fc5e52e54eb806dc4a842ac239b0e6607630"
    },
    {
      "id": "970",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Teatro.",
      "contenido": "Teatro: Talleres Municipales\nTeatro para j\u00f3venes y adultos: Cristina Bismach. Lunes, mi\u00e9rcoles y viernes 20 hs. $54\nTeatro para j\u00f3venes y adultos: Daniela Barros. Jueves 18.30 hs. $54\/\/Talleres Particulares:\nTeatro para ni\u00f1os: Agust\u00edn Gim\u00e9nez. Viernes 18 hs. $100 (desde 8 a\u00f1os)\nComedia musical ni\u00f1os: Rosa C\u00e1ceres \u2013 Eugenia Grillo. Lunes 18 y 19.30 hs. $120",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "9ce4fe0c4802c6d8cc223425578adb2fdc009d5c"
    },
    {
      "id": "971",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Pl\u00e1stica.",
      "contenido": "Pl\u00e1stica: Talleres Municipales:\nArteterapia: J\u00f3venes y Adultos. Beatr\u00edz Caval. Martes y jueves de 9 a 12 hs. $34 (no hay vacantes).\nPl\u00e1stica adultos con materiales reciclados: Beatr\u00edz Caval. Mi\u00e9rcoles 9 a 12 hs. $34\nPl\u00e1stica para ni\u00f1os: M\u00f3nica Mart\u00ednez. S\u00e1bados 10 hs. $34\nIntroducci\u00f3n a la pl\u00e1stica: M\u00f3nica Mart\u00ednez. Viernes 18.30 hs. $100 (desde 8 a\u00f1os)\/\/ Talleres particulares:\n\nDibujo: Claudia Castello. Viernes 9 hs. $150\nPintura Art\u00edstica: Claudia Castello \u2013 Marcela Manzur. Viernes 15 hs. $180\nPintura artesanal: Cecilia Jardel. Martes 12 hs y  S\u00e1bados 9.30 hs. $120\nPintura al pastel adultos: (country \u2013 naif ). Alejandra Valot. Martes 9 hs. $100\nPaisajismo (pincel y esp\u00e1tula): Antonio Zumbo. Martes 14.30 hs. $ 150",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "3977bf30551f730070c93c9d577e63f7baafa97b"
    },
    {
      "id": "972",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "M\u00fasica.",
      "contenido": "M\u00fasica: Talleres Municipales:\nGuitarra: Fernanda Arnut. Lunes y Jueves 9 hs. $105 (cuatrimestre)\nM\u00fasica andina \u2013 charango y quena: Roger Cayre. Viernes 14 hs. (guitarra I), 15 hs. (guitarraII), 16 hs.(quena), 17 hs.(charango). $105 (cuatrimestre)\/\/ Talleres Particulares:\nGuitarra ni\u00f1os: Dar\u00edo Rivero. Viernes 18 y s\u00e1bados 9 hs. $80\nGuitarra: Mart\u00edn Cruz. Jueves 19 hs. $100\nCantoterapia: Alberto Caparotta. Viernes 17.30 hs. $ 90\nCanto: Alicia Begueri. Jueves 18 a 21 hs.  $120\nCanto: H\u00e9ctor Iv\u00e1n Larrea Castillo. Viernes 18 hs. $150\nBateria: Martin Gonzales, Mart\u00edn Morcos Lunes a viernes 14hs. $180\nGuitarra Electrica: Mart\u00edn Morcos Lunes a viernes 10hs. $180",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "34488d026082729dd38ab799064c4c1d363ccfa8"
    },
    {
      "id": "973",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Tejido al crochet y dos agujas, Arte, Fotograf\u00eda, Edici\u00f3n de Im\u00e1genes, Vitraux.",
      "contenido": "Talleres Particulares:\nArte europeo \u2013 arte franc\u00e9s, pintura decorativa y artesania: Celia Abdala. Viernes  9 hs. $150\nTejido al crochet y dos agujas: Teresa Blanch. Lunes 16 hs. y  mi\u00e9rcoles 9 hs. $100\nArte franc\u00e9s -  marqueter\u00eda y falso vitraux: Miriam Cola. Lunes 9 hs y viernes 15 hs.  $120\nCester\u00eda ecol\u00f3gica: Mar\u00eda Lepez. Jueves 9 y de 15 a 18 hs. $100\nVitraux mosaiquismo artesan\u00eda en vidrio: Marisol Alegri. Martes 18 hs. $180. Fotograf\u00eda: Talleres Particulares\nFotograf\u00eda: Adolescente y Adultos. Isa\u00edas Nahman. Martes 14.30 hs. y  s\u00e1bados 10 hs. (cuatrimestral), por mes $180.\nEdici\u00f3n de im\u00e1genes digitales: Isa\u00edas Nahman. Martes 17 hs. y  S\u00e1bados 12 hs. $180",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "d7aedc18d17a83118ffbfb49abd852d3f8de1d3e"
    },
    {
      "id": "974",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Artesan\u00edas.",
      "contenido": "Artesan\u00edas: Talleres Municipales:\nArte textil: Guadalupe Espinosa. Lunes 9 hs. y jueves 15  hs. $34\nMacram\u00e9: Guadalupe Espinosa. Lunes 11.30 hs. y mi\u00e9rcoles 15 hs. $34\nPapel mach\u00e9: M\u00f3nica Mart\u00ednez. Jueves 15 hs. $34\nPorcelana en fr\u00edo: Lilian Di C\u00e9sare. Martes 10.30 hs y mi\u00e9rcoles 17 hs. $34\nReposter\u00eda: Lilian Di C\u00e9sare. Martes 9 hs y mi\u00e9rcoles 15 a 16.30 hs.  $30",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "4100392296a5f74d843f65c8348f03069db88d76"
    },
    {
      "id": "975",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Literatura.",
      "contenido": "Literatura: Talleres Particulares:\nTaller literario: Maximiliano Andrada. Lunes 17 hs. $100\nHistoria del Arte: Lic. Socorro Cubillo. Mi\u00e9rcoles 17 a 19 hs. $220\nCurso de Chino: Prof. Suyai. Lunes y mi\u00e9rcoles 14.30 a 16hs. $180. (No hay vacantes).",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "5f9a20b06b094a047184b87d2cba967c6908d31a"
    },
    {
      "id": "977",
      "titulo": "Talleres Estaci\u00f3n Cultural Ciudad",
      "subtitulo": "Artes marciales.",
      "contenido": "Cursos Particulares:\nKun fu - (ni\u00f1os): Alejandro Tissera. Martes y viernes 18.30 hs. $180\nKun fu \u2013 (adultos): Martes y viernes 20 hs. $180\nTaichi: Alejandro Tissera. Martes y jueves 10.30 a 11.45 hs. $180\nYoga: Viviana Palluca. Martes y jueves 8.30 hs. y 10  hs. $120",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "0",
      "hora_fin": "1435",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "12",
      "lugar_id": "1",
      "agenda_id": "1",
      "group_id": "c2c9ed907bb68719f9718d47d29220b9b5226051"
    },
    {
      "id": "22",
      "titulo": "\u00c1rea Fundacional",
      "subtitulo": "Complejo integrado por el Museo del Area Fundacional, Ruinas de San Francisco y Fuente de la Plaza Pedro del Castillo.",
      "contenido": "Feriados de 11 a 20hs. Lunes cerrado (excepto si es feriado). Entradas con derecho a acceso al museo, c\u00e1mara subterr\u00e1nea y ruinas de San Francisco, Acuario Municipal y Museo Municipal de Arte Moderno.",
      "direccion": "Plaza Pedro del Castillo",
      "telefono": "4256927",
      "mail": "museofundacional@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "124",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "480",
      "hora_fin": "1200",
      "ocultar_hora": "0",
      "permanente": "1",
      "precio": "Entrada general por persona: $20. Entrada para menores de 12 a\u00f1os acompa\u00f1ados por familiar mayor de edad: $9. Estudiantes con carnet de identificaci\u00f3n: $9.Entrada para delegaciones escolares $8 c\/u. Mayores de sesenta y cinco (65) a\u00f1os y menores de tres (3) a\u00f1os acompa\u00f1ados por adultos, discapacitados y menores de doce (12) a\u00f1os con domicilio en la Ciudad de Mendoza: gratis.",
      "categoria_id": "10",
      "lugar_id": "3",
      "agenda_id": "1",
      "group_id": "3aa107a9cd03bcabd46688d00ec6d8cdd6585c98"
    },
    {
      "id": "23",
      "titulo": "Teatro Municipal Julio Quintanilla",
      "subtitulo": "",
      "contenido": "",
      "direccion": "Subsuelo Plaza Independencia (Rivadavia y Mitre)",
      "telefono": "4232310",
      "mail": "teatroquintanilla@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "60",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "480",
      "hora_fin": "840",
      "ocultar_hora": "0",
      "permanente": "1",
      "precio": "",
      "categoria_id": "13",
      "lugar_id": "7",
      "agenda_id": "1",
      "group_id": "b95ed57b7646a18837e39bafe5340262053609d3"
    },
    {
      "id": "24",
      "titulo": "Microcine Municipal David Eisenchlas",
      "subtitulo": "Ciclos de cine gratuitos, talleres, capacitaciones.",
      "contenido": "",
      "direccion": "9 de Julio 500, subsuelo",
      "telefono": "4495255",
      "mail": "microcine@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "62",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "480",
      "hora_fin": "840",
      "ocultar_hora": "0",
      "permanente": "1",
      "precio": "",
      "categoria_id": "2",
      "lugar_id": "2",
      "agenda_id": "1",
      "group_id": "7c111ffbf52a258c062440cfa3c8dfe7a51d14db"
    },
    {
      "id": "31",
      "titulo": "Teatro Municipal Julio Quintanilla",
      "subtitulo": "",
      "contenido": "",
      "direccion": "Subsuelo Plaza Independencia (Rivadavia y Mitre)",
      "telefono": "4232310",
      "mail": "teatroquintanilla@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "64",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "480",
      "hora_fin": "840",
      "ocultar_hora": "0",
      "permanente": "1",
      "precio": "",
      "categoria_id": "13",
      "lugar_id": "7",
      "agenda_id": "1",
      "group_id": "b95ed57b7646a18837e39bafe5340262053609d3"
    },
    {
      "id": "121",
      "titulo": "Terraza Jard\u00edn Mirador",
      "subtitulo": "Se puede observar nuestra Ciudad, desde la hermosa vista que ofrece la terraza.",
      "contenido": "Tiempo estimado 30 minutos. (feriados est\u00e1 abierta de 10 a 13hs.)",
      "direccion": "9 de Julio 500, 7mo piso",
      "telefono": "",
      "mail": "",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "62",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "480",
      "hora_fin": "780",
      "ocultar_hora": "0",
      "permanente": "1",
      "precio": "Gratis.",
      "categoria_id": "15",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "a10454fb711e62a9685ae526a3d23bc7d03e48c1"
    },
    {
      "id": "1464",
      "titulo": "Huarpe",
      "subtitulo": "Expone materiales arqueol\u00f3gicos correspondientes a la ancestral cultura...",
      "contenido": "...originaria que antecedi\u00f3 a la fundaci\u00f3n de la ciudad. En la misma se podr\u00e1n apreciar objetos que pertenecieron a esta etnia adem\u00e1s de informaci\u00f3n actualizada sobre las investigaciones que se realizan en la ciudad de Mendoza y sus alrededores. Recientes hallazgos dan cuenta de una sociedad multifac\u00e9tica que supo adaptarse a desiertos, valles y monta\u00f1as y sobre todo,adecuarse a fuertes procesos de imposici\u00f3n pol\u00edtica hasta la actualidad (inca, espa\u00f1ola y nacional).",
      "direccion": "Plaza Pedro del Castillo",
      "telefono": "4256927",
      "mail": "museofundacional@ciudaddemendoza.gov.ar",
      "web": "",
      "dia_inicio": "19",
      "dia_fin": "30",
      "dias_semana": "124",
      "mes_inicio": "24179",
      "mes_fin": "24183",
      "hora_inicio": "480",
      "hora_fin": "1200",
      "ocultar_hora": "0",
      "permanente": "0",
      "precio": "Entrada general $20, menores de 12 a\u00f1os $9, estudiantes con carnet de identificaci\u00f3n $9, delegaciones escolares $ 8c\/u. Jubilados y escuelas de Mendoza gratis.",
      "categoria_id": "10",
      "lugar_id": "3",
      "agenda_id": "1",
      "group_id": "8652db00155e30f5bcd3f247257b747fbd7c8564"
    },
    {
      "id": "985",
      "titulo": "Bus Vitivin\u00edcola",
      "subtitulo": "El Bus une a Luj\u00e1n de Cuyo \u201cTierra Malbec\u201d y a la Ciudad de Mendoza, \"Capital Internacional del Vino\".",
      "contenido": "Brindando la posibilidad a los pasajeros de conocer m\u00e1s de dos bodegas en un mismo recorrido. Cuenta con el reconocido mecanismo Hop on - Hop off, en el cual el pasajero puede ascender y descender en los sitios que elija. Se ofrecen dos alternativas: mi\u00e9rcoles y viernes se realiza el recorrido \u201cLuj\u00e1n del Sur\u201d ; y \u201cEl Sol\u201d los d\u00edas jueves y s\u00e1bado, visitando diferentes bodegas. Los pasajeros podr\u00e1n armar su recorrido entre visitas a las bodegas, degustaciones, almuerzos y visitas en bicicletas  abonando el costo correspondiente. Para m\u00e1s consultas e informaci\u00f3n puede comunicarse con 0800 122 2282 o ingresando www.busvitivinicola.com.",
      "direccion": "Une a la Ciudad de Mendoza con Luj\u00e1n.",
      "telefono": "Para consultas de horarios o tarifas 0800 122 2282",
      "mail": "",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "120",
      "mes_inicio": "24176",
      "mes_fin": "24176",
      "hora_inicio": "480",
      "hora_fin": "-1",
      "ocultar_hora": "1",
      "permanente": "1",
      "precio": "",
      "categoria_id": "1",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "61671c234f38d2de9393f30a0d933eb59a47c81a"
    },
    {
      "id": "1604",
      "titulo": "Subsidios Fondo Provincial de la Cultura",
      "subtitulo": "Comunicamos que el \u00e1rea de Cultura de la Municipalidad de Capital asesora y\/o recibe proyectos y\/o becas...",
      "contenido": "A partir del 19 de enero 2015 de 8:30 a 13hs. Lic. Alejandra Simoncini y Sra. Cecilia Mancuso. El cierre de la convocatoria es el 21 de marzo 2015 a las 13hs. Bases Generales y Formularios de participaci\u00f3n, www.cultura.mendoza.gov.ar\/FondoProvincialdela Cultura.",
      "direccion": "9 de Julio 500 - Piso 7",
      "telefono": "0261) 449-5255 \/ 5184 \/ 5183",
      "mail": "",
      "web": "",
      "dia_inicio": "19",
      "dia_fin": "21",
      "dias_semana": "62",
      "mes_inicio": "24180",
      "mes_fin": "24182",
      "hora_inicio": "510",
      "hora_fin": "780",
      "ocultar_hora": "0",
      "permanente": "0",
      "precio": "",
      "categoria_id": "3",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "39c5f3e357219bf23771fc7a974fe0aeb29d053e"
    },
    {
      "id": "11",
      "titulo": "Acuario Municipal",
      "subtitulo": "Paseo did\u00e1ctico y divertido imperdible para toda la familia. 40 peceras, tortugo Jorge, reptiles, juegos recreativos y mucho m\u00e1s.",
      "contenido": "Organismo dependiente de la Municipalidad de la Ciudad de Mendoza. \nRecientemente ampliado y remodelado el Acuario Municipal de la Ciudad de Mendoza constituye un paseo did\u00e1ctico y divertido imperdible para toda la familia. 40 peceras, tortugo Jorge, reptiles, juegos recreativos integradores, anfiteatro al aire libre,  pista de manejo para bicicletas, accesos para personas con cualquier tipo de discapacidad.",
      "direccion": "Ituzaing\u00f3 1425",
      "telefono": "4253824",
      "mail": "",
      "web": "",
      "dia_inicio": "1",
      "dia_fin": "31",
      "dias_semana": "127",
      "mes_inicio": "24172",
      "mes_fin": "24172",
      "hora_inicio": "540",
      "hora_fin": "1170",
      "ocultar_hora": "0",
      "permanente": "1",
      "precio": "Entrada general por persona: $20. Entrada para menores de 12 a\u00f1os acompa\u00f1ados por familiar mayor de edad: $9. Estudiantes con carnet de identificaci\u00f3n: $9.Entrada para delegaciones escolares $8 c\/u . Mayores de sesenta y cinco (65) a\u00f1os y menores de tres (3) a\u00f1os acompa\u00f1ados por adultos, discapacitados y menores de doce (12) a\u00f1os con domicilio en la Ciudad de Mendoza: gratis.",
      "categoria_id": "10",
      "lugar_id": "6",
      "agenda_id": "1",
      "group_id": "683619d67b48bc870f04875f99d1fc7fffb03f35"
    }
  ],
  "grupos": {
    "34d4d9c86c7c6d56e6552ba420da437e362194b7": [
      1,
      2
    ],
    "b95ed57b7646a18837e39bafe5340262053609d3": [
      12,
      47,
      14
    ],
    "891cfdbaa29df2ad98ae01b92e9724edddbe8106": [
      20,
      42
    ],
    "e6457c665e799b9c39041144b37794c39d053b9c": [
      66,
      24,
      43
    ],
    "e09933bf6db5e0d0aa55c4bd5eb0a3690a03acee": [
      51,
      27,
      50
    ],
    "9ea3a929559c4ad1738b0f96dd3933c8d2385253": [
      78,
      70
    ],
    "f0e72eebdbfcb549e4001483cd0c9ec477bc8e46": [
      82,
      86,
      84
    ],
    "347966fedb44128f6b988247dc2cd2f661394897": [
      83,
      87,
      85
    ]
  },
  "lugares": [
    {
      "id": "1",
      "lugar": "Estaci\u00f3n Cultural Ciudad",
      "direccion": "Las Heras y Pje. Villalonga",
      "telefono": "4231114",
      "mail": "cultura@ciudaddemendoza.gov.ar",
      "web": ""
    },
    {
      "id": "2",
      "lugar": "Microcine",
      "direccion": "9 de Julio 500, subsuelo",
      "telefono": "4495255",
      "mail": "microcine@ciudaddemendoza.gov.ar",
      "web": ""
    },
    {
      "id": "3",
      "lugar": "Museo de \u00c1rea Fundacional",
      "direccion": "Plaza Pedro del Castillo",
      "telefono": "4256927",
      "mail": "museofundacional@ciudaddemendoza.gov.ar",
      "web": ""
    },
    {
      "id": "4",
      "lugar": "Museo Municipal de Arte Moderno",
      "direccion": "Subsuelo Sur - Plaza Independencia",
      "telefono": "4257279",
      "mail": "mmamm@ciudaddemendoza.gov.ar",
      "web": ""
    },
    {
      "id": "5",
      "lugar": "Nave Cultural",
      "direccion": "Av. Espa\u00f1a y Maza, Parque Central",
      "telefono": "4495288",
      "mail": "navecultural@ciudaddemendoza.gov.ar",
      "web": ""
    },
    {
      "id": "7",
      "lugar": "Teatro Quintanilla",
      "direccion": "Subsuelo Plaza Independencia (Rivadavia y Mitre)",
      "telefono": "4232310",
      "mail": "teatroquintanilla@ciudaddemendoza.gov.ar",
      "web": ""
    },
    {
      "id": "6",
      "lugar": "Otros",
      "direccion": "",
      "telefono": "",
      "mail": "",
      "web": ""
    }
  ],
  "categorias": [
    {
      "id": "1",
      "categoria": "Capital Internacional del Vino"
    },
    {
      "id": "2",
      "categoria": "Cine"
    },
    {
      "id": "3",
      "categoria": "Concursos \/ Convocatorias"
    },
    {
      "id": "5",
      "categoria": "Danza"
    },
    {
      "id": "6",
      "categoria": "Ferias"
    },
    {
      "id": "7",
      "categoria": "Fiestas populares"
    },
    {
      "id": "8",
      "categoria": "Historia \/ Ciencia \/ Letras"
    },
    {
      "id": "10",
      "categoria": "Muestras"
    },
    {
      "id": "11",
      "categoria": "M\u00fasica"
    },
    {
      "id": "12",
      "categoria": "Talleres"
    },
    {
      "id": "13",
      "categoria": "Teatro"
    },
    {
      "id": "14",
      "categoria": "T\u00edteres"
    },
    {
      "id": "15",
      "categoria": "Visitas Guiadas"
    },
    {
      "id": "16",
      "categoria": "Otros"
    }
  ]
};

// Returns all the faqs ( curl -X GET localhost:3333/faqs/ )
exports.getAll = function(req, res) {
	console.log(req);
	res.json(datos);
};